In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv('data.xls')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54808 entries, 0 to 54807
Data columns (total 14 columns):
employee_id             54808 non-null int64
department              54808 non-null object
region                  54808 non-null object
education               52399 non-null object
gender                  54808 non-null object
recruitment_channel     54808 non-null object
no_of_trainings         54808 non-null int64
age                     54808 non-null int64
previous_year_rating    50684 non-null float64
length_of_service       54808 non-null int64
KPIs_met >80%           54808 non-null int64
awards_won?             54808 non-null int64
avg_training_score      54808 non-null int64
is_promoted             54808 non-null int64
dtypes: float64(1), int64(8), object(5)
memory usage: 5.9+ MB


In [4]:
df.dropna(inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 48660 entries, 0 to 54807
Data columns (total 14 columns):
employee_id             48660 non-null int64
department              48660 non-null object
region                  48660 non-null object
education               48660 non-null object
gender                  48660 non-null object
recruitment_channel     48660 non-null object
no_of_trainings         48660 non-null int64
age                     48660 non-null int64
previous_year_rating    48660 non-null float64
length_of_service       48660 non-null int64
KPIs_met >80%           48660 non-null int64
awards_won?             48660 non-null int64
avg_training_score      48660 non-null int64
is_promoted             48660 non-null int64
dtypes: float64(1), int64(8), object(5)
memory usage: 5.6+ MB


In [6]:
df.head()

employee_id         department     region         education gender  \
0        65438  Sales & Marketing   region_7  Master's & above      f   
1        65141         Operations  region_22        Bachelor's      m   
2         7513  Sales & Marketing  region_19        Bachelor's      m   
3         2542  Sales & Marketing  region_23        Bachelor's      m   
4        48945         Technology  region_26        Bachelor's      m   

  recruitment_channel  no_of_trainings  age  previous_year_rating  \
0            sourcing                1   35                   5.0   
1               other                1   30                   5.0   
2            sourcing                1   34                   3.0   
3               other                2   39                   1.0   
4               other                1   45                   3.0   

   length_of_service  KPIs_met >80%  awards_won?  avg_training_score  \
0                  8              1            0                  49   
1                  4              0            0                  60   
2                  7              0            0                  50   
3                 10              0            0                  50   
4                  2              0            0                  73   

   is_promoted  
0            0  
1            0  
2            0  
3            0  
4            0

In [7]:
df.drop('employee_id',axis=1,inplace=True)

In [8]:
from sklearn.feature_selection import chi2

In [9]:
df.head()

department     region         education gender recruitment_channel  \
0  Sales & Marketing   region_7  Master's & above      f            sourcing   
1         Operations  region_22        Bachelor's      m               other   
2  Sales & Marketing  region_19        Bachelor's      m            sourcing   
3  Sales & Marketing  region_23        Bachelor's      m               other   
4         Technology  region_26        Bachelor's      m               other   

   no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   35                   5.0                  8   
1                1   30                   5.0                  4   
2                1   34                   3.0                  7   
3                2   39                   1.0                 10   
4                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
0              1            0                  49            0  
1              0            0                  60            0  
2              0            0                  50            0  
3              0            0                  50            0  
4              0            0                  73            0

In [10]:
df=df.reset_index(drop=True)

In [11]:
df.head()

department     region         education gender recruitment_channel  \
0  Sales & Marketing   region_7  Master's & above      f            sourcing   
1         Operations  region_22        Bachelor's      m               other   
2  Sales & Marketing  region_19        Bachelor's      m            sourcing   
3  Sales & Marketing  region_23        Bachelor's      m               other   
4         Technology  region_26        Bachelor's      m               other   

   no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   35                   5.0                  8   
1                1   30                   5.0                  4   
2                1   34                   3.0                  7   
3                2   39                   1.0                 10   
4                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  is_promoted  
0              1            0                  49            0  
1              0            0                  60            0  
2              0            0                  50            0  
3              0            0                  50            0  
4              0            0                  73            0

In [12]:
df.describe()

no_of_trainings           age  previous_year_rating  length_of_service  \
count     48660.000000  48660.000000          48660.000000        48660.00000   
mean          1.251993     35.589437              3.337526            6.31157   
std           0.604994      7.534571              1.257922            4.20476   
min           1.000000     20.000000              1.000000            1.00000   
25%           1.000000     30.000000              3.000000            3.00000   
50%           1.000000     34.000000              3.000000            5.00000   
75%           1.000000     39.000000              4.000000            8.00000   
max          10.000000     60.000000              5.000000           37.00000   

       KPIs_met >80%  awards_won?  avg_training_score   is_promoted  
count   48660.000000  48660.00000        48660.000000  48660.000000  
mean        0.356473      0.02314           63.603309      0.086971  
std         0.478962      0.15035           13.273502      0.281795  
min         0.000000      0.00000           39.000000      0.000000  
25%         0.000000      0.00000           51.000000      0.000000  
50%         0.000000      0.00000           60.000000      0.000000  
75%         1.000000      0.00000           76.000000      0.000000  
max         1.000000      1.00000           99.000000      1.000000

In [17]:
x=df.drop('is_promoted',axis=1)
y=df['is_promoted']

In [19]:
x=pd.get_dummies(x,drop_first=True)

In [20]:
x.head()

no_of_trainings  age  previous_year_rating  length_of_service  \
0                1   35                   5.0                  8   
1                1   30                   5.0                  4   
2                1   34                   3.0                  7   
3                2   39                   1.0                 10   
4                1   45                   3.0                  2   

   KPIs_met >80%  awards_won?  avg_training_score  department_Finance  \
0              1            0                  49                   0   
1              0            0                  60                   0   
2              0            0                  50                   0   
3              0            0                  50                   0   
4              0            0                  73                   0   

   department_HR  department_Legal  ...  region_region_5  region_region_6  \
0              0                 0  ...                0                0   
1              0                 0  ...                0                0   
2              0                 0  ...                0                0   
3              0                 0  ...                0                0   
4              0                 0  ...                0                0   

   region_region_7  region_region_8  region_region_9  \
0                1                0                0   
1                0                0                0   
2                0                0                0   
3                0                0                0   
4                0                0                0   

   education_Below Secondary  education_Master's & above  gender_m  \
0                          0                           1         0   
1                          0                           0         1   
2                          0                           0         1   
3                          0                           0         1   
4                          0                           0         1   

   recruitment_channel_referred  recruitment_channel_sourcing  
0                             0                             1  
1                             0                             0  
2                             0                             1  
3                             0                             0  
4                             0                             0  

[5 rows x 53 columns]

In [23]:
p

(array([8.89480850e+00, 3.89885434e+01, 5.81142029e+02, 2.77442043e+01,
        1.51467663e+03, 1.84419587e+03, 4.34266449e+03, 6.85237545e-01,
        2.50631415e+01, 1.62073427e+01, 4.54828379e+00, 1.02239211e+01,
        5.45350351e+00, 2.81411815e+01, 3.19895018e+01, 5.98100489e-01,
        1.32791460e+01, 3.56106421e+00, 1.63986519e-02, 1.62489816e+00,
        6.59631805e-01, 4.92610531e+00, 2.13502412e+01, 6.20338915e-01,
        8.57082491e+00, 3.55473346e+00, 8.42043135e+00, 7.84220119e+00,
        5.66155583e+01, 1.47705555e+01, 1.34104446e+01, 2.05420522e+01,
        1.18354458e+01, 4.76470186e-01, 1.47528620e+01, 2.47057242e+01,
        2.56614624e+00, 3.84894405e-02, 1.72590712e+01, 1.48865420e+01,
        7.70486054e+00, 9.76116626e+00, 7.37549859e+01, 1.53597481e+01,
        1.29026480e+01, 2.56253301e+01, 1.16383374e-02, 1.58261935e+01,
        4.03897479e-01, 2.63628830e+01, 2.10017304e+00, 2.10487569e+01,
        1.78118766e-02]),
 array([2.85982597e-003, 4.26299943e-0

In [21]:
p=chi2(x,y)

In [22]:
p[1]<0.05

array([ True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False, False, False,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True, False,  True, False])